added errWriter so getting a shelfWriter no longer returns an error
nuts-foundation/go-stoabs pull request #38
Opened 2022-12-05 14:43 UTC by woutslakhorst

Got a bit tired with all the error checking when getting shelves....

2022-12-06 09:37 UTC, gerardsn requested changes
Just noting that we now have a`NilReader` and `errWriter` that are specific to bbolt

2022-12-06 09:37 UTC, gerardsn commented on store.go
> +	return errWriter{err: err}
The error should probably be wrapped in `ErrDatabase`?

2022-12-06 09:37 UTC, gerardsn commented on store.go
> +	// Returns a ErrWriter if unsuccessful.
`errWriter` is private

2022-12-06 09:37 UTC, gerardsn commented on store.go
> +// ErrWriter is a shelfWriter that already failed, but to reduce the error count it'll fail on the write operation
```suggestion
// errWriter is a shelfWriter that already failed, but to reduce the error count it'll fail on the write operation
```

2022-12-06 14:37 UTC, reinkrul requested changes

2022-12-07 09:29 UTC, gerardsn approved these changes

2022-12-07 09:31 UTC, gerardsn commented
Maybe add test to confirm that returned errors are `ErrDatabase` errors

2022-12-08 07:30 UTC, merged