added afterCommit on tx
nuts-foundation/go-stoabs pull request #6
Opened 2022-06-17 05:55 UTC by woutslakhorst

This is needed when a tx is passed through methods.

2022-06-17 07:31 UTC, gerardsn approved these changes

2022-06-20 07:08 UTC, reinkrul requested changes
Without having looked into why it is required, I think this is very confusing and breaks the current design, where you specify TX lifecycle hooks (after rollback/commit) using options when starting the TX. And I think it introduces a second lifecycle hook (seemingly abstract) which is BBolt specific (because probably not implementable with e.g. Redis), (so not really an abstract hook).

2022-06-20 09:46 UTC, woutslakhorst commented
> Without having looked into why it is required, I think this is very confusing and breaks the current design, where you specify TX lifecycle hooks (after rollback/commit) using options when starting the TX. And I think it introduces a second lifecycle hook (seemingly abstract) which is BBolt specific (because probably not implementable with e.g. Redis), (so not really an abstract hook).

There might be a possibility to work around things, I'll come back later

2022-06-20 10:20 UTC, woutslakhorst commented
Rewrote stuff, no longer needed

2022-06-20 10:20 UTC, closed without merging